<html>
<head>
</head>
<body>
<h1>PAGARE</h1>

<table width="100%" border="1px" cellspacing="0px">
<theader>
<th>NÚMERO</th><th>LUGAR DE EMISIÓN</th><th>FECHA DE EMISION</th><th>FECHA DE VENCIMIENTO</th><th>MONEDA</th><th>IMPORTE</th>
</theader>
<tbody>
<tr><td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
Por este <b>PAGARE</b> debo(emos) y pagare(mos) solidaria e incondicionalmente a la orden de <b>CREDITOS ALIANZA C & B</b> con <b>RUC 20000000000</b>, en su domicilio social o donde se me(nos) presentare a cobro, o a quien ésta empresa se lo hubiese transferido mi deuda; por la cantidad de:
<table border="1px" cellspacing="0px">
<tr><td>00/100 NUEVOS SOLES</td></tr>
</table>
Importe a debitar en las oficinas de <b>CREDITOS ALIANZA C & B</b> ubicadas en la <b>DIRECCION</b><table width="100%" cellspacing="0px">
<tr><td>
<h2>CLAUSULAS ESPECIALES</h2>
A. Este pagaré esta normado por la Ley 27287 Ley de Títulos Valores y sus respectivas modificatorias.
B. Este pagaré debe ser pagado en la misma moneda que expresa el título valor.
C. A su vencimiento podrá ser prorrogado por su tenedor por el plazo que éste señale en este mismo documento, sin que sea necesaria intervención alguna del obligado principal ni del Aval solidario.
D. El presente pagaré puede ser cedido por parte de "CREDITOS ALIANZA C & B" a terceros, asumiendo este último el derecho de exigir el cumplimiento de todas las obligaciones establecidas en el presente documento para lo cual (el) los obligados dan su aceptación.
E. Desde su último vencimiento, su importe total y/o cuotas, generará los intereses compensatorios, más los intereses moratorios a las tasas máximas autorizadas o permitidas a su último tenedor.
F. El presente pagaré no requiere ser protestado por falta de pago, procediendo su ejecución por el sólo mérito de haber vencido su plazo y no haber sido prorrogado. Así como en caso de incumplimiento de una o más cuotas se faculta al tenedor a dar por vencido todos los plazos en cuyo caso procederá el protesto antes de su vencimiento.
G. El importe de este pagaré será pagado en los montos de las cuotas que se señalan el documento en hoja adherida, denominado "Cronograma de Préstamo Individual", los pagos serán en cuotas diarias, semanales, quincenales y/o mensuales según lo estipulado y/o acordado con el cliente.
H.El importe de este pagaré y/o de las cuotas pactadas, desde su fecha de emisión hasta la fecha de su respectivo vencimiento generará un interés compensatorio a la tasa de interés legal vigente.
I: Los pagos parciales o totales de las cuotas, podrán ser verificados en CREDITOS ALIANZA C & B.
</td></tr>
</table>
</body>
</html>