<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
     '<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n".
     '<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
     <script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
     <script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
     <script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
     <keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
     <script>
function f_capturarRecibo(){
     new Ajax.Request( 
                      '<?=$this->url(array('action'=>'anularecibo'))?>',
    { method:'post',
        parameters: {op:'get',COD:$('COD').value}, 
        onSuccess: function(t) {
        r=t.responseJSON;
        if (r.code==0){ 
          if (r.data==null) f_limpiar();
          else{
          $('COD').value=r.data.COD;
          $('CREDITO_COD').value=r.data.CREDITO_COD;
          $('CLIENTE_COD').value=r.data.CLIENTE_COD;
          $('CLIENTE_NOM').value=r.data.CLIENTE_NOM;
          $('MONTO').value=r.data.MONTO;
          }
        } 
      } 
      } );
   }
function f_anular(){
  new Ajax.Request( 
                     '<?=$this->url(array('action'=>'anularecibo'))?>',
                   { method:'post',
                       parameters: {op:'ins',COD:$('COD').value,OBS:$('OBS').value}, 
                       onSuccess: function(t) {
                       r=t.responseJSON;
                       alert(r.msg);
                       if (r.code==0){ 
                         f_limpiar()
                       } 
                     } 
                     } );
}
function f_limpiar(){
          $('COD').value='';
          $('CREDITO_COD').value='';
          $('CLIENTE_COD').value='';
          $('CLIENTE_NOM').value='';
          $('MONTO').value=''
            $('OBS').value='';
          $('COD').focus();

}
     </script>
     <groupbox>
     <caption label='<?=$this->subTitle?>' />
     <grid>
     <columns>
     <column />
     <column />
     </columns>
     <rows>
     <row><label value='Recibo #' control='COD'/><textbox id='COD' maxlength='12' size="20" onchange="f_capturarRecibo()"/></row>
     <row><label value='Crédito' control='CREDITO_COD'/><textbox id='CREDITO_COD' maxlength='12' size="12" readonly="true"/></row>

     <row><label value='Cliente' control='CLIENTE_COD'/><hbox><textbox id='CLIENTE_COD' maxlength='12' readonly="true" size="12"/> <textbox id='CLIENTE_NOM' readonly="true" size="30"/></hbox></row>
     <row><label value='Monto' control='MONTO'/><textbox id='MONTO' maxlength='11' readonly="true"/></row>
     <row><label value='Motivo' control='OBS'/><textbox id='OBS' multiline="true" rows="5"/></row>
     </rows>
     </grid>
     <hbox><button label='Anular' image='<?=$this->baseUrl()?>/www/img/icons/delete.png' oncommand="f_anular()"/></hbox>
     </groupbox>
     </window>