<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n".
'<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
<script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
<script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
<script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
<keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
<script>
Quipu.tree=$('tr');
function f_desembolsar(){
  Quipu.tree=$('tr');
  val=Quipu.getTreeValue();
  if (val!=null){
    window.location.href='<?=$this->url(array('action'=>'desembolsocredito'))?>?COD='+val;
  }
}
function f_anular(){
  Quipu.tree=$('tr');
  val=Quipu.getTreeValue();
  new Ajax.Request( 
                   '<?=$this->url(array('module'=>'credito','controller'=>'credito','action'=>'anular'))?>',
                   { method:'post',
                       parameters: {COD:val}, 
                       onSuccess: function(t) {
                       r=t.responseJSON;
                       alert(r.msg);
                       if (r.code==0){ 
                         Quipu.treeDelete();
                       } 
                     } 
                     } );
  
}
</script>
<groupbox orient="horizontal">
<caption label='<?=$this->subTitle?>' />
<tree id="tr" flex="1" enableColumnDrag="true" rows="20">
<treecols>
<treecol label="Código" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="DNI o RUC" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Nombres y Apellidos" flex="3"/>
<splitter class="tree-splitter" />
<treecol label="Plazo" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Monto" flex="1"/>
</treecols>
<treechildren>
<? foreach($this->desembolsos as $desembolso) {?>
<treeitem>
<treerow>
<treecell label="<?=$desembolso->K_COD?>" />
<treecell label="<?=$desembolso->K_DOC?>" />
<treecell label="<?=$desembolso->K_NOM?>" />
<treecell label="<?=$desembolso->K_PLAZO?>" />
<treecell label="<?=$desembolso->K_MONTO?>" />
</treerow>
</treeitem>
<? } ?>
</treechildren>
</tree>
<vbox>
<button label="Desembolsar" image="<?=$this->baseUrl()?>/www/img/icons/ok.png" oncommand="f_desembolsar()"/>
<button label="Anular" image="<?=$this->baseUrl()?>/www/img/icons/delete.png" oncommand="f_anular()"/>
</vbox>
</groupbox>
</window>