<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
     '<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n".
     '<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
  <script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
  <script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
  <script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
  <keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
  <script>
function f_generar(){
     Quipu.print('<?=$this->url(array('action'=>'ingresosalidafecharep'))?>/COD/'+$('COD').value+'/FEC_DESDE/'+$('FEC_DESDE').value+'/FEC_HASTA/'+$('FEC_HASTA').value+'/MON/'+$('MON').value+'/FERIADO/'+$('FERIADO').value,null,'<?=$this->baseUrl()?>');
}
  </script>
  <groupbox>
    <caption label='<?=$this->subTitle?>' />
     <grid>
     <columns>
     <column />
     <column />
     </columns>
     <rows>
     <row><label value='Empleado' control='COD'/>
     <menulist id='COD'>
     <menupopup>
     <?foreach ($this->empleados as $empleado){?>
     <menuitem label='<?=$empleado->NOM_LARGO?>' value='<?=$empleado->COD?>' />
                                               <?}?>
     <menuitem label='TODOS' value=''/>
     </menupopup>
     </menulist></row>
     <row><label value='Desde' control='FEC_DESDE'/><datepicker id='FEC_DESDE' value="<?=date('Y-m-d')?>" type="popup"/></row>
     <row><label value='Hasta' control='FEC_HASTA'/><datepicker id='FEC_HASTA' value="<?=date('Y-m-d')?>" type="popup"/></row>
     <row><label value='Moneda' control='MON'/>
     <menulist id='MON'>
     <menupopup>
     <?foreach ($this->monedas as $moneda){?>
     <menuitem label='<?=$moneda->NOM?>' value='<?=$moneda->COD?>' />
                                           <? }?>
     </menupopup>
     </menulist></row>
     <row><label value='Sólo días no laborable' control='FERIADO'/><checkbox id="FERIADO" label=''/></row>
     </rows>
     </grid>
     <hbox><button label="Generar" image="<?=$this->baseUrl()?>/www/img/icons/ok.png" oncommand="f_generar()"/></hbox>
  </groupbox>
</window>
