<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
<script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
<script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
<script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
<keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
<script>
</script>
<groupbox>
<caption label='<?=$this->subTitle?>' />

</groupbox>
</window>