<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n"
.'<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' onload="f_cargar()">
<script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
<script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
<script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
<keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
<script>
Quipu.url='<?=$this->url(array('controller'=>'credito','action'=>'buscar'))?>';
function f_cargar(){
  $('valor').focus();
}
function f_buscar(){
  //  Quipu.list=$('lb');
  Quipu.tree=$('tr');
  Quipu.cargarLista({opc:$('opc').value, valor:$('valor').value, est: '<?=$this->est?>'});
}
function f_capturar(cod){
  window.opener.<?=$this->f?>(cod);
  setTimeout("window.close()",Quipu.tiempoEspera);
}
</script>
<groupbox>
<caption label='<?=$this->subTitle?>' />
<hbox>
<menulist id='opc'>
<menupopup>
<menuitem label='Por Nombres' value='2' />
<menuitem label='Por DNI ó RUC' value='3' />
<menuitem label='Por Código de Cliente' value='4' />
<menuitem label='Por Código de Crédito' value='1' />
</menupopup>
</menulist>
<textbox id='valor' maxlength='100' flex="1"/>
<button label="Buscar" image="<?=$this->baseUrl()?>/www/img/icons/search.png" oncommand="f_buscar()"/>
</hbox>
<tree id="tr" flex="1" enableColumnDrag="true" onselect="f_capturar(Quipu.getTreeValue())" rows="10">
<treecols>
<treecol label="Código" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="DNI o RUC" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Nombres y Apellidos" flex="3"/>
<splitter class="tree-splitter" />
<treecol label="Plazo" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Monto" flex="1"/>
</treecols>
<treechildren>
</treechildren>
</tree>
</groupbox>
</window>