<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
     '<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n".
     '<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
     <script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
     <script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
     <script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
     <keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
     <script>
     function f_guardar(){
     new Ajax.Request( 
                      '<?=$this->url(array('action'=>'cambiarmora'))?>',
    { method:'post',
        parameters: {COD:$('COD').value, TI_MORA:$('TI_MORA').value,TI_COMPENSA:$('TI_COMPENSA').value,opc:'upd'},
        onSuccess: function(t) {
        r=t.responseJSON;
        alert(r.msg);
        if (r.code==0){ 
          $('COD').value='';
          $('TI_COMPENSA').value='';
          $('TI_MORA').value=''
             $('COD').focus();
        } 
      } 
      } );
}
function f_buscar_credito(){
  Quipu.open("<?=$this->url(array('controller'=>'credito','action'=>'buscardesembolso'))?>?f=f_capturar_credito");
}
function f_capturar_credito(cod){
  if(cod!=''){
     new Ajax.Request( 
                      '<?=$this->url(array('action'=>'cambiarmora'))?>',
    { method:'post',
        parameters: {opc:'get', COD:cod}, 
        onSuccess: function(t) {
        r=t.responseJSON;
        if (r.code==0){ 
          $('COD').value=r.data.COD;
          $('TI_COMPENSA').value=r.data.TI_COMPENSA;
          $('TI_MORA').value=r.data.TI_MORA;
        } 
      } 
      } );
  }
}

     </script>
     <groupbox>
     <caption label='<?=$this->subTitle?>' />
     <grid>
     <columns>
     <column />
     <column />
     </columns>
     <rows>
     <row><label value='Crédito' control='COD'/><hbox><textbox id='COD' maxlength='12' onchange='f_capturar_credito(this.value)'/><button label='' image='<?=$this->baseUrl()?>/www/img/icons/search.png' oncommand='f_buscar_credito()'/></hbox></row>
     <row><label value='T. Moratoria' control='TI_MORA'/><textbox id='TI_MORA' maxlength='11'/></row>
     <row><label value='T. Compensatoria' control='TI_COMPENSA'/><textbox id='TI_COMPENSA' maxlength='11'/></row>
     </rows>
     </grid>
     <hbox><button label='Guardar' image='<?=$this->baseUrl()?>/www/img/icons/ok.png' oncommand='f_guardar()'/></hbox>
     </groupbox>
     </window>
