<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n".
'<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
  <script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
  <script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
  <script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
  <keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
  <script>
function f_buscar_cliente(){
  var bcliente=window.open("<?=$this->url(array('controller'=>'cliente','action'=>'buscar'))?>?f=f_capturar_cliente","bc","chrome,dialog,modal,titlebar=no,height=400,width=600");
  bcliente.creator=self;
}
function f_buscar_codigo_cliente(obj){
  if (obj==null) obj=$('CLIENTE_COD');
  if (obj.value==''){
    f_buscar_cliente()
  }
  else{
    f_capturar_cliente(obj.value);
  }
}
function f_capturar_cliente(cod){
  new Ajax.Request( 
                   '<?=$this->url(array('action'=>'estadocredito'))?>',
                   { method:'post',
                       parameters: {COD: cod}, 
                       onSuccess: function(t) {
                       r=t.responseJSON;
                       if (r.code==0){ 
                         cliente=r.data['cliente'];
                         $('CLIENTE_COD').value=cliente.COD;
                         $('CLIENTE_NOM').value=cliente.NOM_LARGO;
                         Quipu.treeAdd($('tr'),r.data['credito']);
                       } 
                     } 
                     } );
}
function f_reporte(){
  credito=Quipu.getTreeValue($('tr'));
  if (credito!=null){
    Quipu.print('<?=$this->url(array('action'=>'estadocreditorep'))?>/COD/'+credito,null, '<?=$this->baseUrl()?>');
  }
}
function f_get_credito(){
   cr=Quipu.getTreeValue($('tr'));
   return cr;
}
function f_cronograma(){
  credito=f_get_credito();
  url="<?=$this->url(array('controller'=>'cronograma','action'=>'desembolso'))?>/COD/"+credito;
  Quipu.print(url,null,'<?=$this->baseUrl()?>');
}
function f_pagare(){
  credito=f_get_credito();
  url="<?=$this->url(array('module'=>'legal','controller'=>'credito','action'=>'pagarecliente'))?>/COD/"+credito;
  Quipu.print(url,null,'<?=$this->baseUrl()?>');
}
function f_contrato(){
  credito=f_get_credito();
  url="<?=$this->url(array('module'=>'legal','controller'=>'credito','action'=>'contratocliente'))?>/COD/"+credito;
  Quipu.print(url,null,'<?=$this->baseUrl()?>');
}
function f_solicitud(){
  credito=f_get_credito();
  url="<?=$this->url(array('module'=>'legal','controller'=>'credito','action'=>'solicitudcliente'))?>/COD/"+credito;
  Quipu.print(url,null,'<?=$this->baseUrl()?>');
}
function f_cartanotarial(){
  credito=f_get_credito();
  url="<?=$this->url(array('module'=>'legal','controller'=>'credito','action'=>'cartanotarial'))?>/COD/"+credito;
  Quipu.print(url,null,'<?=$this->baseUrl()?>');
}
function f_transaccion_extrajudicial(){
  credito=f_get_credito();
  url="<?=$this->url(array('module'=>'legal','controller'=>'credito','action'=>'transaccionextrajudicialrep'))?>/COD/"+credito;
  Quipu.print(url,null,'<?=$this->baseUrl()?>');
}
  </script>
  <groupbox>
    <caption label='<?=$this->subTitle?>' />
    <grid>
      <columns>
        <column />
        <column />
      </columns>
      <rows>
        <row><label value='Cliente' control='CLIENTE_COD'/><hbox><textbox id='CLIENTE_COD' maxlength='12' size="12" onblur="f_capturar_cliente(this.value)"/><textbox id='CLIENTE_NOM' size="40" readonly="true"/><button image="<?=$this->baseUrl()?>/www/img/icons/search.png" oncommand="f_buscar_cliente()"/></hbox></row>
      </rows>
    </grid>
    <tree id="tr" flex="1" enableColumnDrag="true" onselect="" rows="10">
      <treecols>
        <treecol label="Código" flex="1"/>
        <splitter class="tree-splitter" />
        <treecol label="Fecha" flex="1"/>
        <splitter class="tree-splitter" />
        <treecol label="Desembolso" flex="1"/>
        <splitter class="tree-splitter" />
        <treecol label="Analista" flex="4"/>
        <splitter class="tree-splitter" />
        <treecol label="Cuotas" flex="1"/>
        <splitter class="tree-splitter" />
        <treecol label="Monto" flex="1"/>
        <splitter class="tree-splitter" />
        <treecol label="E"/>
      </treecols>
      <treechildren>
      </treechildren>
    </tree>
  <hbox><button label="Generar Informe de Crédito" image="<?=$this->baseUrl()?>/www/img/icons/ok.png" oncommand="f_reporte()"/>
  <button label="Documentos" type="menu">
  <menupopup>
         <menuitem label="Cronograma" oncommand="f_cronograma()" />
         <menuitem label="Solicitud" oncommand="f_solicitud()" />
         <menuitem label="Contrato" oncommand="f_contrato()" />
         <menuitem label="Pagare" oncommand="f_pagare()" />
  <separator/>
       <menuitem label="Carta Notarial" oncommand="f_cartanotarial()" />
         <menuitem label="Transacción Extrajudicial" oncommand="f_transaccion_extrajudicial()" />
       </menupopup>

</button>
  </hbox>
  </groupbox>
</window>
