<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n"
.'<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";

?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' onload="f_cargar()" >
<script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
<script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
<script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
<keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
<script>
Quipu.campos=new Array('FEC_INI','FEC_FIN','IGV','RENTA','ITF');
//Quipu.campos_primarios=new Array('ID');
Quipu.url='<?=$this->url(array('action'=>'impuesto'))?>';
Quipu.foco='IGV';
Quipu.defecto={FEC_INI:'<?=$this->fec_ini?>'};
var v=new Validate();
v.addRules({id:'FEC_INI', required: true, option: 'date', label: 'Fecha de Inicio'});
v.addRules({id:'FEC_FIN', required: false, option: 'date', label: 'Fecha de Termino'});
v.addRules({id:'IGV', required: true, option: 'Decimal', label: 'IGV'});
v.addRules({id:'ITF', required: true, option: 'Decimal', label: 'ITF'});
v.addRules({id:'SEGURO', required: true, option: 'Decimal', label: 'Seguro de Desgravamen'});
v.addRules({id:'RENTA', required: true, option: 'Decimal', label: 'Renta'});

function f_cargar(){
  //  Quipu.list=$('lb');
  Quipu.tree=$('tr');
  $('IGV').focus();
  Quipu.cargarLista({op:'get'});
}
function f_cargar_uno(cod){
  Quipu.cargarUno({op:'get', idx:cod});
  $('IGV').focus();
}
function f_guardar(){
  if (v.Apply()){
    if(Quipu.ultimo_registro==null)
      Quipu.guardarRegistro(Quipu.toParams('FEC_INI','FEC_FIN','IGV','ITF','SEGURO','RENTA',{op: 'ins'}));
    else{
      Quipu.guardarRegistro(Quipu.toParams('FEC_INI','FEC_FIN','IGV','ITF','SEGURO','RENTA',{op: 'upd', idx:Quipu.ultimo_registro.COD}));
    }
  }
}
function f_eliminar(){
  Quipu.eliminarRegistro({op: 'del', idx: Quipu.getTreeValue()});
}

</script>
<groupbox>
<caption label='<?=$this->subTitle?>' />

  <hbox>
    <vbox>
      <grid>
        <columns>
          <column/>
          <column/>
        </columns>
        <rows>
          <row><label value="Fecha de Inicio" control="FEC_INI"/> <datepicker id="FEC_INI" value="<?=date('Y-m-d')?>" type="popup"/></row>
<row><label value='IGV (%)' control='IGV'/><textbox id='IGV' maxlength='11'/></row>
<row><label value='ITF(%)' control='ITF'/><textbox id='ITF' maxlength='11'/></row>
<row><label value='SEG. DESGRAVAMEN (%)' control='SEGURO'/><textbox id='SEGURO' maxlength='11'/></row>
<row><label value='RENTA (%)' control='RENTA'/><textbox id='RENTA' maxlength='11'/></row>
        </rows>
      </grid>
      <hbox><button id="btnGuardar" label="Guardar" image="<?=$this->baseUrl()?>/www/img/icons/ok.png" oncommand="f_guardar()" /></hbox>
    </vbox>
    <hbox flex="1">
<tree id="tr" flex="1" enableColumnDrag="true" onselect="f_cargar_uno(Quipu.getTreeValue())" rows="10">
<treecols>
<treecol label="Código"/>
<splitter class="tree-splitter" />
<treecol label="Fec. Inicio" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Fec. de Termino" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="IGV" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="ITF" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Seguro" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Renta" flex="1"/>
</treecols>
</tree>
    </hbox>
  </hbox>
</groupbox>
</window>