<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n"
.'<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";

?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' onload="f_cargar()" >
<script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
<script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
<script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
<keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
<script>
Quipu.campos=new Array('COD','NOM','TI_MENSUAL','TI_MORA','TI_COMPENSA','GA','MONEDA_COD','MONTO_MIN','MONTO_MAX','CUOTA_MIN','CUOTA_MAX');
Quipu.campos_primarios=new Array('COD');
Quipu.url='<?=$this->url(array('action'=>'linea'))?>';
var v=new Validate();
v.addRules({id:'COD', required: true, option: 'Alpha', label: 'Código'});
v.addRules({id:'NOM', required: true, option: 'Alpha', label: 'Nombre'});
v.addRules({id:'TI_MENSUAL', required: true, option: 'Decimal', label: 'Tasa Mensual'});
v.addRules({id:'TI_MORA', required: true, option: 'Decimal', label: 'Tasa Moratoria'});
v.addRules({id:'TI_COMPENSA', required: true, option: 'Decimal', label: 'Tasa Compensatoria'});

v.addRules({id:'GA', required: true, option: 'Decimal', label: 'G.Administrativos'});
v.addRules({id:'MONTO_MIN', required: true, option: 'Decimal', label: 'G.Administrativos'});
v.addRules({id:'MONTO_MAX', required: true, option: 'Decimal', label: 'G.Administrativos'});
v.addRules({id:'CUOTA_MIN', required: true, option: 'Number', label: 'G.Administrativos'});
v.addRules({id:'CUOTA_MAX', required: true, option: 'Number', label: 'G.Administrativos'});
function f_cargar(){
  //  Quipu.list=$('lb');
  Quipu.tree=$('tr');
  $('COD').focus();
  Quipu.cargarLista({op:'get'});
}
function f_cargar_uno(cod){
  Quipu.cargarUno({op:'get', idx:cod});
  $('COD').focus();
}
function f_guardar(){
  if (v.Apply()){
    if(Quipu.ultimo_registro==null)
      Quipu.guardarRegistro(Quipu.toParams('COD','NOM','TI_MENSUAL','TI_MORA','TI_COMPENSA','GA','MONEDA_COD','MONTO_MIN','MONTO_MAX','CUOTA_MIN','CUOTA_MAX',{op: 'ins'}));
    else{
      Quipu.guardarRegistro(Quipu.toParams('COD','NOM','TI_MENSUAL','TI_MORA','TI_COMPENSA','GA','MONEDA_COD','MONTO_MIN','MONTO_MAX','CUOTA_MIN','CUOTA_MAX',{op: 'upd', idx:Quipu.ultimo_registro.COD}));
    }
  }
}
function f_eliminar(){
  Quipu.eliminarRegistro({op: 'del', idx: Quipu.getTreeValue()});
}

</script>
<groupbox>
<caption label='<?=$this->subTitle?>' />

  <hbox>
    <vbox>
      <grid>
        <columns>
          <column/>
          <column/>
        </columns>
        <rows>
          <row><label value="Código" control="COD"/> <textbox maxlength="12" id="COD" tabindex="1"/></row>
          <row><label value="Nombre" control="NOM"/> <textbox maxlength="255" id="NOM" oninput="this.value=this.value.toUpperCase()" tabindex="2"/></row>
          <row><label value="Moneda" control="MONEDA_COD"/> 
               <menulist id="MONEDA_COD" tabindex="3">
                  <menupopup>
                      <? foreach($this->monedas as $moneda){?>
                          <menuitem label="<?=$moneda->NOM?>" value="<?=$moneda->COD?>"/>
                      <? }?>
                  </menupopup>
               </menulist>
          </row>
          <row><label value="Tasa Mensual (%)" control="TI_MENSUAL"/> <textbox maxlength="11" id="TI_MENSUAL" tabindex="4"/></row>
          <row><label value="Tasa Moratoria (%)" control="TI_MORA"/> <textbox maxlength="11" id="TI_MORA" tabindex="5"/></row>
          <row><label value="Tasa Compensatoria (%)" control="TI_COMPENSA"/> <textbox maxlength="11" id="TI_COMPENSA"  tabindex="6"/></row>
          <row><label value="G.Administrativo (S./)" control="GA"/> <textbox maxlength="11" id="GA" tabindex="7"/></row>
          <row><label value="Monto Mínimo" control="MONTO_MIN"/> <textbox maxlength="11" id="MONTO_MIN" tabindex="8"/></row>
          <row><label value="Monto Máximo" control="MONTO_MAX"/> <textbox maxlength="11" id="MONTO_MAX" tabindex="9"/></row>
          <row><label value="Cuota Mínima" control="CUOTA_MIN"/> <textbox maxlength="11" id="CUOTA_MIN" tabindex="10"/></row>
          <row><label value="Cuota Máxima" control="CUOTA_MAX"/> <textbox maxlength="11" id="CUOTA_MAX" tabindex="11"/></row>

        </rows>
      </grid>
      <hbox><button id="btnGuardar" label="Guardar" image="<?=$this->baseUrl()?>/www/img/icons/ok.png" oncommand="f_guardar()" /></hbox>
    </vbox>
    <hbox flex="1">
<tree id="tr" flex="1" enableColumnDrag="true" onselect="f_cargar_uno(Quipu.getTreeValue())" rows="10">
<treecols>
<treecol label="Código"/>
<splitter class="tree-splitter" />
<treecol label="Nombre" flex="1"/>
</treecols>
</tree>
      <vbox><button image="<?=$this->baseUrl()?>/www/img/icons/new.png" oncommand="Quipu.nuevoRegistro()"/> <button image="<?=$this->baseUrl()?>/www/img/icons/delete.png" oncommand="f_eliminar()"/></vbox>
    </hbox>
  </hbox>
</groupbox>
</window>