<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n"
.'<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";

?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' onload="f_cargar()">
<script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
<script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
<script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
<keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
<script>
Quipu.campos=new Array('COD','DNI','NOM','APE_PAT','APE_MAT','DIRE','FONO1','TIPO_EMPLEADO_COD','FEC_INI','FEC_TER','AGENCIA_COD','USR','ROL');
Quipu.campos_primarios=new Array('COD');
Quipu.url='<?=$this->url(array('action'=>'empleado'))?>';
var v=new Validate();
v.addRules({id:'COD', required: true, option:'Alpha', label: 'Código'});
v.addRules({id:'DNI', required: true, option:'Alpha', label: 'DNI'});
v.addRules({id:'NOM', required: true, option:'Alpha', label: 'Nombre'});
v.addRules({id:'APE_PAT', required: true, option:'Alpha', label: 'Apellido Paterno'});
v.addRules({id:'APE_MAT', required: true, option:'Alpha', label: 'Apellido Materno'});
v.addRules({id:'DIRE', required: true, option:'Alpha', label: 'Dirección'});
v.addRules({id:'FONO1', required: true, option:'Alpha', label: 'Télefono'});
v.addRules({id:'FEC_INI', required: true, option:'date', label: 'Fecha de Inicio'})
v.addRules({id:'FEC_TER', option:'date', label: 'Fecha de Termino'});
function f_cargar(){
  //  Quipu.list=$('lbEmpleado');
  Quipu.tree=$('trEmpleado');
  Quipu.foco=$('DNI');
  $('DNI').focus();
  Quipu.cargarLista({op:'get'});
}
function f_cargar_uno(cod){
  Quipu.cargarUno({op:'get', idx:cod});
  $('DNI').focus();
}
function f_guardar(){
  if ($('COD').value=='') {$('COD').value=$('DNI').value;}
  if (v.Apply()){
    if(Quipu.ultimo_registro==null){
      Quipu.guardarRegistro(Quipu.toParams('COD','DNI','NOM','APE_PAT','APE_MAT','DIRE','FONO1','TIPO_EMPLEADO_COD','FEC_INI','FEC_TER','AGENCIA_COD','USR','ROL',{op: 'ins'}));
    }
    else{
      Quipu.guardarRegistro(Quipu.toParams('COD','DNI','NOM','APE_PAT','APE_MAT','DIRE','FONO1','TIPO_EMPLEADO_COD','FEC_INI','FEC_TER','AGENCIA_COD','USR','ROL',{op: 'upd', idx:Quipu.ultimo_registro.COD}));
    }
  }
  setTimeout('f_cargarCodigo()',Quipu.tiempoEspera);
}
function f_eliminar(){
  Quipu.eliminarRegistro({op: 'del', idx: Quipu.getTreeValue()});
  setTimeout('f_cargarCodigo()',Quipu.tiempoEspera);
}
function f_nuevo(){
  Quipu.nuevoRegistro();
  setTimeout('f_cargarCodigo()',Quipu.tiempoEspera);
}
function f_cargarCodigo(){
  new Ajax.Request( 
                   '<?=$this->url(array('action'=>'empleado'))?>',
  { method:'post',
             parameters: {op:'cod'}, 
             onSuccess: function(t) {
               r=t.responseJSON;
               if (r.code==0){ 
                 $('COD').value=r.data;
               } 
             } 
  } );
}
</script>
<groupbox>
  <caption label='<?=$this->subTitle?>' />
  <hbox>
    <vbox>
      <grid>
        <columns>
          <column/>
          <column/>
        </columns>
        <rows>
          <row><label value="Código" control="COD"/> <textbox id="COD" maxlength="12" readonly="true" value="<?=$this->cod?>"/></row>
          <row><label value="DNI" control="DNI"/> <textbox id="DNI" maxlength="8"/></row>

          <row><label value="Nombres" control="NOM"/> <textbox id="NOM" maxlength="40" oninput="this.value=this.value.toUpperCase()"/></row>
          <row><label value="Apellido Paterno" control="APE_PAT"/> <textbox id="APE_PAT" maxlength="40" oninput="this.value=this.value.toUpperCase()" /></row>
          <row><label value="Apellido Materno" control="APE_MAT"/> <textbox id="APE_MAT" maxlength="40" oninput="this.value=this.value.toUpperCase()"/></row>
          <row><label value="Dirección" control="DIRE"/> <textbox id="DIRE" maxlength="100" oninput="this.value=this.value.toUpperCase()" /></row>
          <row><label value="Télefono" control="FONO1"/> <textbox id="FONO1" maxlength="25"/></row>
          <row><label value="Agencia" control="AGENCIA_COD"/> 
               <menulist id="AGENCIA_COD">
                   <menupopup>
                   <? foreach($this->agencias as $agencia){ ?>
                       <menuitem value="<?=$agencia->COD?>" label="<?=$agencia->NOM?>"/>                     
                   <? }?> 
                   </menupopup>
               </menulist>
          </row>

          <row><label value="Tipo de Empleado" control="TIPO_EMPLEADO_COD"/> 
               <menulist id="TIPO_EMPLEADO_COD">
                   <menupopup>
                   <? foreach($this->tipoEmpleado as $tipoEmpleado){ ?>
                       <menuitem value="<?=$tipoEmpleado->COD?>" label="<?=$tipoEmpleado->NOM?>"/>                     
                   <? }?> 
                   </menupopup>
               </menulist>
               </row>
          <row><label value="Fecha de Ingreso" control="FEC_INI"/> <datepicker id="FEC_INI" type="popup"/></row>
          <row><label value="Fecha de Término" control="FEC_TER"/> <datepicker id="FEC_TER" type="popup"/></row>
                   <row><label value="Usuario" control="USR"/><textbox id="USR" maxlength="32"/></row>
                   <row><label  value="Contraseña"/><label value="Por defecto igual que el Usuario"/></row>
                   <row><label value="Rol" control="ROL"/>
                   <menulist id="ROL">
                   <menupopup>
                   <? foreach($this->roles as $rol){
                     ?>
                     <menuitem value="<?=$rol->COD?>" label="<?=$rol->NOM?>"/>
                   <? } ?>
                   </menupopup>
                   </menulist>
                   </row>
        </rows>
      </grid>
      <hbox><button label="Guardar" oncommand="f_guardar()" image="<?=$this->baseUrl()?>/www/img/icons/ok.png"/></hbox>
    </vbox>
    <hbox flex="1">
<tree id="trEmpleado" flex="1" enableColumnDrag="true" onselect="f_cargar_uno(Quipu.getTreeValue())" rows="10">
<treecols>
<treecol label="Código" flex="1"/>
<splitter class="tree-splitter" />
<treecol label="Nombre" flex="2"/>
</treecols>
</tree>
       <vbox><button image="<?=$this->baseUrl()?>/www/img/icons/new.png" oncommand="f_nuevo()"/> <button image="<?=$this->baseUrl()?>/www/img/icons/delete.png" oncommand="f_eliminar()"/></vbox>
    </hbox>
  </hbox>
</groupbox>
</window>
