<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
  <script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
  <script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
  <script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
  <keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
  <script>
    function loadPage(url){
    $("frmContenido").setAttribute('src',url);
    }
    function f_salir(){
    window.location.href='<?=$this->baseUrl()?>';
    }
  </script>
  <menubar>
    <menu label="Caja">
      <menupopup>
        <menuitem label="Desembolso" oncommand="loadPage('<?=$this->url(array('controller'=>'caja','action'=>'desembolsolista'))?>')"/>
        <menuitem label="Recibo de Pago" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'caja','action'=>'pagocuota'))?>')"/>
        <menuitem label="Recibo General" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'caja','action'=>'recibo'))?>')"/>
      </menupopup>
    </menu>
    <menu label="Configuración">
      <menupopup>
        <menuitem label="Personal" oncommand="loadPage('<?=$this->url(array('module'=>'auth','controller'=>'config','action'=>'personal'))?>')"/>
      </menupopup>
    </menu>

    <menu label="Reportes">
      <menupopup>
        <menuitem label="Historial de Crédito" oncommand="loadPage('<?=$this->url(array('controller'=>'credito','action'=>'estadocredito'))?>')"/>
        <menuitem label="Reporte de Ingresos y Salida" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'caja','action'=>'ingresosalidadiatotal'))?>')"/>
        <menuitem label="Reporte de Mora" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'cobranza','action'=>'mora'))?>')"/>
        <menuitem label="Reporte de Economico" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'credito','action'=>'economico'))?>')"/>
        <menuitem label="Reporte de Capital" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'reporte','action'=>'capital'))?>')"/>
        <menuitem label="Reporte General de Impuestos" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'reporte','action'=>'igvitf'))?>')"/>
        <menuitem label="Reporte de Cartera Activa" oncommand="loadPage('<?=$this->url(array('module'=>'credito','controller'=>'reporte','action'=>'carteraactiva'))?>')"/>

      </menupopup>
    </menu>
    <menu label="Ayuda">
      <menupopup>
      <menuitem label="Ayuda" oncommand="Quipu.open('<?=$this->baseUrl()?>/docs/manual.pdf')"/>
        <menuitem label="Acerca de ..."/>
        <menuseparator/>
        <menuitem label="Salir" oncommand="f_salir()"/>
      </menupopup>
    </menu>
  </menubar>
  <toolbox>
    <toolbar>
      <toolbarbutton image="<?=$this->baseUrl()?>/www/img/icons/password.png" oncommand="loadPage('<?=$this->url(array('module'=>'auth','controller'=>'config','action'=>'personal'))?>')" />
      <toolbarbutton image="<?=$this->baseUrl()?>/www/img/icons/close.png" oncommand="f_salir()" />
    </toolbar>
  </toolbox>
  <iframe id="frmContenido" flex="2"  minheight="400px"></iframe>
</window>
