<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n"
.'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n";
?>
<window
id="login_window"
title="<?=$this->title.' - '.$this->subTitle;?>"
orient="vertical"
xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul" onload="f_cargar()">
<script src="<?=$this->baseUrl()?>/www/js/prototype_xul.js"/>
<script src="<?=$this->baseUrl()?>/www/js/validate.prototype.js"/>
<script src="<?=$this->baseUrl()?>/www/js/quipu_xul.js"/>
<keyset>
    <key keycode="VK_RETURN" oncommand="if (document.commandDispatcher.focusedElement.tagName!='button') document.commandDispatcher.advanceFocus();"/>
</keyset>
<script>
function f_cargar(){
  $("u").focus();
}
function f_login(){
new Ajax.Request( '<?=$this->url(array('action'=>'index'))?>',
{
	method: 'post',
	parameters: {u:$('u').value, p:$('p').value},
	onSuccess: function(t)	{
       if(t.responseJSON.code==1){//errores
         alert(t.responseJSON.msg);
         $('u').value='';
         $('p').value='';
         $('u').focus();
       }
       else{ 
         window.location.href=t.responseJSON.url;
       }
    }
}
);
}
</script>
<groupbox>
<caption label="<?=$this->subTitle?>"/>
<hbox>
  <vbox>
    <label value="Usuario" control="u"/>
    <label value="Contraseña" control="p"/>
  </vbox>
  <vbox>
    <textbox id="u" maxlength="32" value="<?=$this->identity->USR?>"/>
    <textbox id="p" type="password" maxlength="32"/>
  </vbox>
</hbox>
<hbox>
    <button id="btnIngresar" label="Ingresar" oncommand="f_login()"/>
    <button id="btnSalir" label="Salir" oncommand="window.close()"/>
</hbox>
</groupbox>
<script>$('u').focus()</script>
</window>
