<?='<?xml version="1.0" encoding="'.$this->encoding.'"?>'."\n".
'<?xml-stylesheet href="chrome://global/skin/" type="text/css"?>'."\n".
  '<?xml-stylesheet href="'.$this->baseUrl().'/www/css/view.css" type="text/css"?>'."\n";
?>
<window title='<?=$this->title.' : '.$this->subTitle?>' orient='vertical' xmlns='http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul' >
  <script src='<?=$this->baseUrl()?>/www/js/prototype_xul.js'/>
  <script src='<?=$this->baseUrl()?>/www/js/validate.prototype.js' />
  <script src='<?=$this->baseUrl()?>/www/js/quipu_xul.js' />
  <keyset><key keycode='VK_RETURN' oncommand='if (document.commandDispatcher.focusedElement.tagName!="button") document.commandDispatcher.advanceFocus();'/></keyset>
  <script>
  function f_sincronizar(){
  $('btn').disabled=true;
  new Ajax.Request( 
                   '<?=$this->url(array('action'=>'index'))?>',
    { method:'post',
        parameters: {}, 
        onSuccess: function(t) {
        r=t.responseJSON;
        alert(r.msg);
        $('btn').disabled=false;
        if (r.code==0){ 
          
        } 
      } 
      } );
}
  </script>
  <groupbox>
  <caption label='<?=$this->subTitle?>' />
  <row>
  <button id='btn' label='Sincronizar' image='<?=$this->baseUrl()?>/www/img/icons/cronograma.png' oncommand="f_sincronizar()"/></row>
  </groupbox>
  </window>